enable auto correction of corrupt vm data

diff --git a/deployments/base/metrics/helm-release.yaml b/deployments/base/metrics/helm-release.yaml
--- a/deployments/base/metrics/helm-release.yaml
+++ b/deployments/base/metrics/helm-release.yaml
@@ -28,50 +28,70 @@ spec:
         name: vm
       version: 0.20.0
   interval: 1m0s
-  values:
-    vmselect:
-      podAnnotations:
-        prometheus.io/scrape: "true"
-        prometheus.io/port: "8481"
-    vminsert:
-      podAnnotations:
-        prometheus.io/scrape: "true"
-        prometheus.io/port: "8480"
-    vmstorage:
-      initContainers:
-        - name: cleanup-broken-parts
-          image: alpine:3.19
-          command:
-            - /bin/sh
-            - -c
-            - |
-              echo "🔍 Scanning for corrupted metadata.json files..."
-              apk add --no-cache jq find coreutils
-              find /vmstorage-data/data -type f -name metadata.json | while read f; do
-                if ! jq empty "$f" >/dev/null 2>&1; then
-                  echo "⚠️ Invalid JSON: $f"
-                  echo "🧹 Deleting corrupted part: $(dirname "$f")"
-                  rm -rf "$(dirname "$f")"
-                fi
-              done
-              echo "✅ Cleanup complete."
-          volumeMounts:
-            - name: victoria-metrics
-              mountPath: /vmstorage-data
-      replicaCount: 1
-      retentionPeriod: 12
-      persistentVolume:
-        accessModes:
-          - ReadWriteMany
-        name: victoria-metrics
-        enabled: true
-        existingClaim: victoria-metrics
-        storageClassName: nfs
-        size: 200Gi
-        mountPath: /vmstorage-data
-      podAnnotations:
+  values: {}
+---
+apiVersion: operator.victoriametrics.com/v1beta1
+kind: VMCluster
+metadata:
+  name: vmcluster
+  namespace: monitoring
+spec:
+  retentionPeriod: "1"
+  replicationFactor: 1
+
+  vmstorage:
+    podAnnotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "8482"
+    replicaCount: 1
+    image:
+      repository: victoriametrics/vmstorage
+      tag: v1.115.0
+    volumeMounts:
+      - name: vmstorage-data
+        mountPath: /vmstorage-data
+    volumes:
+      - name: vmstorage-data
+        persistentVolumeClaim:
+          claimName: victoria-metrics
+    initContainers:
+      - name: cleanup-broken-parts
+        image: alpine:3.19
+        command:
+          - /bin/sh
+          - -c
+          - |
+            echo "🔍 Scanning for corrupted metadata.json files..."
+            apk add --no-cache jq find coreutils
+            find /vmstorage-data/data -type f -name metadata.json | while read f; do
+              if ! jq empty "$f" >/dev/null 2>&1; then
+                echo "⚠️ Invalid JSON: $f"
+                echo "🧹 Deleting corrupted part: $(dirname "$f")"
+                rm -rf "$(dirname "$f")"
+              fi
+            done
+            echo "✅ Cleanup complete."
+        volumeMounts:
+          - name: vmstorage-data
+            mountPath: /vmstorage-data
+
+  vmselect:
+    podAnnotations:
+        prometheus.io/scrape: "true"
+        prometheus.io/port: "8481"
+    replicaCount: 1
+    image:
+      repository: victoriametrics/vmselect
+      tag: v1.115.0
+
+  vminsert:
+    podAnnotations:
+        prometheus.io/scrape: "true"
+        prometheus.io/port: "8480"
+    replicaCount: 1
+    image:
+      repository: victoriametrics/vminsert
+      tag: v1.115.0
 ---
 apiVersion: helm.toolkit.fluxcd.io/v2
 kind: HelmRelease
